<?php require($templates_path . 'admin/header.php'); ?>
<h2><?php e($object['title']); ?></h2>
<?php if(isset($object['mib']['uname']['nodename']))
{
	echo '<p class="nodename">' . _e($object['mib']['uname']['nodename']) . '</p>';
}
?>
<?php

if(isset($object['mib']['uname']))
{
	echo '<div class="uname">';
	echo '<h3>' . _e($object['mib']['uname']['opsys'] . ' ' . $object['mib']['uname']['release']) . '</h3>';
	echo '<p>' . _e($object['mib']['uname']['version'] . ' — ' . $object['mib']['uname']['machine']) . '</p>';
	echo '</div>';
}

if(isset($object['mib']['fs']))
{

function fromblocks($n)
{
	if($n >= 1048576)
	{
		return round($n / 1048576) . '&nbsp;Gi';
	}
	if($n >= 1024)
	{
		return round($n / 1024) . '&nbsp;Mi';
	}
	if(!$n)
	{
		return 0;
	}
	return $n . '&nbsp;Ki';
}

?>
<div class="item-list-container">

	<div class="item-list">
		<table>
			<thead>
				<tr>
					<th scope="col">Special</th>
					<th scope="col">Total</th>
					<th scope="col">Used</th>
					<th scope="col">Available</th>
					<th scope="col">Capacity</th>
					<th scope="col">Mountpoint</th>
				</tr>
			</thead>
			<tbody>
			<?php
			$odd = true;
			foreach($object['mib']['fs'] as $fs)
			{
				echo '<tr class="' . ($odd ? 'odd ':'even ') . '">';
				echo '<td>' . _e($fs['device']) . '</td>';
				echo '<td>' . fromblocks($fs['total']) . '</td>';
				echo '<td>' . fromblocks($fs['used']) . '</td>';
				echo '<td>' . fromblocks($fs['available']) . '</td>';
				echo '<td>' . _e($fs['capacity']) . '%</td>';
				echo '<td>' . _e($fs['mountpoint']) . '</td>';
				echo '</tr>';
				$odd = !$odd;
			}
			?>
			</tbody>
		</table>
	</div>
</div>
<?php
}
?>
<?php require($templates_path . 'admin/footer.php'); ?>